language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - PATH=$PATH:./vendor/bin

cache:
  directories:
    - vendor/

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

before_script:
  - composer self-update

install:
  - composer install

script:
  - composer checkerror
  - composer inspect
  - composer checkstyle
  - composer test
